name: Deploy to PROD

on:
  push:
    branches:
      - main 

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod   

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Replace ENV placeholder
        run: sed -i 's/{{ENV_NAME}}/PROD/' index.html

      - name: Deploy to PROD EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_SERVER }}
          username: ec2-user
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "index.html"
          target: "/usr/share/nginx/html/"
